#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
   path: /
   controller: App\Controller\AdminController::indexAdmin

indexAdmin:
   path: /index
   controller: App\Controller\AdminController::indexAdmin

login:
   path: /login
   controller: App\Controller\SecurityController::login

adduser:
   path: /registration
   controller: App\Controller\RegistrationController::adduser

listUser:
   path: /listuser
   controller: App\Controller\RegistrationController::listUser

addEn:
   path: /addEn
   controller: App\Controller\AdminController::addEnseignant

addEt:
   path: /addEt
   controller: App\Controller\AdminController::addEtudiant

addBt:
   path: /addBt
   controller: App\Controller\AdminController::addBatiment

addUn:
   path: /addUn
   controller: App\Controller\AdminController::addUniversite

addSa:
   path: /addSa
   controller: App\Controller\AdminController::addSalle

logout:
   path: /logout
   controller: App\Controller\SecurityController::logout
