#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
   path: /index
   controller: App\Controller\UserController::indexAdmin

login:
   path: /login
   controller: App\Controller\SecurityController::login

adduser:
   path: /registration
   controller: App\Controller\RegistrationController::adduser

